SET NOCOUNT ON

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'SourceTypes')
BEGIN
	PRINT 'Create SourceTypes table'
	CREATE TABLE [dbo].[SourceTypes] (
		Id BIGINT CONSTRAINT PK_SourceTypes_Id PRIMARY KEY IDENTITY(1,1) NOT NULL,
		Name NVARCHAR(100) NOT NULL
		
	)
END
GO

SET NOCOUNT OFF

