SET NOCOUNT ON
USE Emigrace

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Countries')
BEGIN
	PRINT 'Create Countries table'
	CREATE TABLE [dbo].[Countries] (
		Id BIGINT CONSTRAINT PK_Countries_Id PRIMARY KEY IDENTITY(1,1) NOT NULL,
		Name NVARCHAR(100) NOT NULL
		)

END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'States')
BEGIN
	PRINT 'Create States table'
	CREATE TABLE [dbo].[States] (
		Id BIGINT CONSTRAINT PK_States_Id PRIMARY KEY IDENTITY(1,1) NOT NULL,
		Name NVARCHAR(100) NOT NULL,
		CountryId BIGINT NOT NULL,
		CONSTRAINT FK_States_CountryId FOREIGN KEY(CountryId) REFERENCES Countries(Id)
		)

END
GO


IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Counties')
BEGIN
	PRINT 'Create Counties table'
	CREATE TABLE [dbo].[Counties] (
		Id BIGINT CONSTRAINT PK_Counties_Id PRIMARY KEY IDENTITY(1,1) NOT NULL,
		Name NVARCHAR(100) NOT NULL,
		StateId BIGINT NOT NULL,
		CONSTRAINT FK_Counties_StateId FOREIGN KEY(StateId) REFERENCES States(Id)
		
		)

END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Cities')
BEGIN
	PRINT 'Create Cities table'
	CREATE TABLE [dbo].[Cities] (
		Id BIGINT CONSTRAINT PK_Cities_Id PRIMARY KEY IDENTITY(1,1) NOT NULL,
		Name NVARCHAR(100) NOT NULL,
		CountyId BIGINT NOT NULL,
		CONSTRAINT FK_Cities_CountyId FOREIGN KEY(CountyId) REFERENCES Counties(Id),
		OldName BIT NOT NULL 
		)

END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Connections')
BEGIN
	PRINT 'Create Connections table'
	CREATE TABLE [dbo].[Connections] (
		Id BIGINT CONSTRAINT PK_Connections_Id PRIMARY KEY IDENTITY(1,1) NOT NULL,
		PlaceId BIGINT NOT NULL,
		SynonymPlaceId BIGINT NOT NULL,
		CONSTRAINT FK_Connections_PlaceId FOREIGN KEY(PlaceId) REFERENCES Cities(Id),
		CONSTRAINT FK_Connections_SynonymPlaceId FOREIGN KEY(SynonymPlaceId) REFERENCES Cities(Id)
		)

END
GO



SET NOCOUNT OFF
