SET NOCOUNT ON
USE Emigrace

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Archives')
BEGIN
	PRINT 'Create Archives table'
	CREATE TABLE [dbo].[Archives] (

		Id BIGINT CONSTRAINT PK_Archives_Id PRIMARY KEY IDENTITY(1,1) NOT NULL,
		Name NVARCHAR(200) NOT NULL,
		Adress NVARCHAR(150) NOT NULL,
		Country NVARCHAR(50) NOT NULL,
		Phone NVARCHAR(30) NULL, 
		WebPages VARCHAR(50) NULL
		)
END
GO
SET NOCOUNT OFF
	